package analizador_lexico;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diego Pérez Moir
 */
public enum Token {
    HALT_COMPILER, ABSTRACT, AND, ARRAY, AS, BREAK, CALLABLE, CASE, CATCH, CLASS
    , CLONE, CONST, CONTINUE, DECLARE, DEFAULT, DIE, DO, ECHO, ELSE, ELSEIF, EMPTY
    , ENDDECLARE, ENDFOR, ENDFOREACH, ENDIF, ENDSWITCH, ENDWHILE, EVAL, EXIT, EXTENDS,
    FINAL, FOR, FOREACH, FUNCTION, GLOBAL, GOTO, IF, IMPLEMENTS, INCLUDE, INCLUDE_ONCE, 
    INSTANCEOF, INSTEADOF, INTERFACE, ISSET, LIST, NAMESPACE, NEW, OR, PRINT, PRIVATE, 
    PROTECTED, PUBLIC, REQUIRE, REQUIRE_ONCE, RETURN, STATIC, SWITCH, THROW, TRAIT, TRY, 
    UNSET, USE, VAR, WHILE, XOR, DOUBLE_COLON, ARROW, INCR, DECR, IDENTICAL, EQUAL, NOT_IDENTICAL,
    NOT_EQUAL, GREATER_EQUAL, LESS_EQUAL, PLUSS_EQUAL, MINUS_EQUAL, MULT_EQUAL, DIV_EQUAL, POW_EQUAL,
    CONCAT_EQUAL, MOD_EQUAL, SL, SR, SL_EQUAL, SR_EQUAL, AND_EQUAL, OR_EQUAL, XOR_EQUAL, SYM_OR, 
    SYM_AND, SEMICOLON, COLON, COMMA, DOT, RECT_OPEN_BRACE, RECT_CLOSE_BRACE, OPEN_BRACE, CLOSE_BRACE,
    OPEN_CURLY_BRACE, CLOSE_CURLY_BRACE, BIT_OR, BIT_XOR, BIT_AND, PLUS, MINUS, DIV, MULT, POW, ASSING,
    MOD, NOT, BIT_NOT, DOLLAR, LESS, GREATER, AT, INI, CLOSE , ERROR, NUMBER, REAL_NUM, ID, COMMENT, STRING,
    C_CONSTANT; 
}
